name: my_own_planner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/images/planner.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/images/emptybox.png
  uses-material-design: true

